#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# added by travis gem
[ -f /Users/chaofei/.travis/travis.sh ] && source /Users/chaofei/.travis/travis.sh
